[package]
name = "traffic_volume"
version = "0.1.0"
authors = ["Philip Van Raalte <phil.vanraalte@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
mongodb = "0.3.12"
