version: "3"
services:
  mongo:
    image: mongo:latest
    restart: "no"
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    links:
      - mongo
  rust:
    build: .
    volumes:
      - ./:/usr/local/app/
    ports:
      - 8080:8080
    links:
      - mongo
    command: /usr/local/app/scripts/entrypoint.sh
