[package]
name = "traffic"
version = "0.1.0"
authors = ["Philip Van Raalte <phil.vanraalte@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
juniper = "0.15"