[package]
name = "traffic_records"
version = "0.1.0"
authors = ["Philip Van Raalte <phil.vanraalte@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.7"
mongodb = "0.3.12"
bson = "0.13"
traffic = { path = "../traffic" }